# This is the configuration used to check the rubocop source code.

Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

Style/AlignHash:
  EnforcedColonStyle: table

Style/Encoding:
  EnforcedStyle: when_needed
